### Create new booking
POST http://localhost:4004/api/booking
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name" : "Vi",
  "email" : "vi@example.com",
  "bookTime" : "2025-09-05T15:40:00",
  "table" : "3"
}
###