### Create new booking
POST http://localhost:4004/api/booking
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name" : "Vin",
  "email" : "vin@example.com",
  "bookTime" : "2025-10-05T15:40:00",
  "table" : "3"
}
###