FROM nginx:alpine


COPY ./decor.png /usr/share/nginx/html/decor.png
COPY ./background.png /usr/share/nginx/html/background.png
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
