### Crete new user
POST http://localhost:4004/auth/register
Content-Type: application/json

{
  "username": "user3",
  "email": "user3@example.com",
  "password": "secret3"
}

> {% client.global.set("token", response.body.token) %}
###