### Crete new user
POST http://localhost:4004/auth/register
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@example.com",
  "password": "secret2"
}

> {% client.global.set("token", response.body.token) %}
###